// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Example is an object representing the database table.
type Example struct {
	ID         int    `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name       string `boil:"name" json:"name" toml:"name" yaml:"name"`
	Occupation string `boil:"occupation" json:"occupation" toml:"occupation" yaml:"occupation"`
	Telephone  string `boil:"telephone" json:"telephone" toml:"telephone" yaml:"telephone"`
	Email      string `boil:"email" json:"email" toml:"email" yaml:"email"`
	Notes      string `boil:"notes" json:"notes" toml:"notes" yaml:"notes"`

	R *exampleR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L exampleL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ExampleColumns = struct {
	ID         string
	Name       string
	Occupation string
	Telephone  string
	Email      string
	Notes      string
}{
	ID:         "id",
	Name:       "name",
	Occupation: "occupation",
	Telephone:  "telephone",
	Email:      "email",
	Notes:      "notes",
}

var ExampleTableColumns = struct {
	ID         string
	Name       string
	Occupation string
	Telephone  string
	Email      string
	Notes      string
}{
	ID:         "example.id",
	Name:       "example.name",
	Occupation: "example.occupation",
	Telephone:  "example.telephone",
	Email:      "example.email",
	Notes:      "example.notes",
}

// Generated where

var ExampleWhere = struct {
	ID         whereHelperint
	Name       whereHelperstring
	Occupation whereHelperstring
	Telephone  whereHelperstring
	Email      whereHelperstring
	Notes      whereHelperstring
}{
	ID:         whereHelperint{field: "\"example\".\"id\""},
	Name:       whereHelperstring{field: "\"example\".\"name\""},
	Occupation: whereHelperstring{field: "\"example\".\"occupation\""},
	Telephone:  whereHelperstring{field: "\"example\".\"telephone\""},
	Email:      whereHelperstring{field: "\"example\".\"email\""},
	Notes:      whereHelperstring{field: "\"example\".\"notes\""},
}

// ExampleRels is where relationship names are stored.
var ExampleRels = struct {
}{}

// exampleR is where relationships are stored.
type exampleR struct {
}

// NewStruct creates a new relationship struct
func (*exampleR) NewStruct() *exampleR {
	return &exampleR{}
}

// exampleL is where Load methods for each relationship are stored.
type exampleL struct{}

var (
	exampleAllColumns            = []string{"id", "name", "occupation", "telephone", "email", "notes"}
	exampleColumnsWithoutDefault = []string{"name", "occupation", "telephone", "email", "notes"}
	exampleColumnsWithDefault    = []string{"id"}
	examplePrimaryKeyColumns     = []string{"id"}
	exampleGeneratedColumns      = []string{}
)

type (
	// ExampleSlice is an alias for a slice of pointers to Example.
	// This should almost always be used instead of []Example.
	ExampleSlice []*Example
	// ExampleHook is the signature for custom Example hook methods
	ExampleHook func(context.Context, boil.ContextExecutor, *Example) error

	exampleQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	exampleType                 = reflect.TypeOf(&Example{})
	exampleMapping              = queries.MakeStructMapping(exampleType)
	examplePrimaryKeyMapping, _ = queries.BindMapping(exampleType, exampleMapping, examplePrimaryKeyColumns)
	exampleInsertCacheMut       sync.RWMutex
	exampleInsertCache          = make(map[string]insertCache)
	exampleUpdateCacheMut       sync.RWMutex
	exampleUpdateCache          = make(map[string]updateCache)
	exampleUpsertCacheMut       sync.RWMutex
	exampleUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var exampleAfterSelectMu sync.Mutex
var exampleAfterSelectHooks []ExampleHook

var exampleBeforeInsertMu sync.Mutex
var exampleBeforeInsertHooks []ExampleHook
var exampleAfterInsertMu sync.Mutex
var exampleAfterInsertHooks []ExampleHook

var exampleBeforeUpdateMu sync.Mutex
var exampleBeforeUpdateHooks []ExampleHook
var exampleAfterUpdateMu sync.Mutex
var exampleAfterUpdateHooks []ExampleHook

var exampleBeforeDeleteMu sync.Mutex
var exampleBeforeDeleteHooks []ExampleHook
var exampleAfterDeleteMu sync.Mutex
var exampleAfterDeleteHooks []ExampleHook

var exampleBeforeUpsertMu sync.Mutex
var exampleBeforeUpsertHooks []ExampleHook
var exampleAfterUpsertMu sync.Mutex
var exampleAfterUpsertHooks []ExampleHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Example) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range exampleAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Example) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range exampleBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Example) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range exampleAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Example) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range exampleBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Example) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range exampleAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Example) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range exampleBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Example) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range exampleAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Example) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range exampleBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Example) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range exampleAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddExampleHook registers your hook function for all future operations.
func AddExampleHook(hookPoint boil.HookPoint, exampleHook ExampleHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		exampleAfterSelectMu.Lock()
		exampleAfterSelectHooks = append(exampleAfterSelectHooks, exampleHook)
		exampleAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		exampleBeforeInsertMu.Lock()
		exampleBeforeInsertHooks = append(exampleBeforeInsertHooks, exampleHook)
		exampleBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		exampleAfterInsertMu.Lock()
		exampleAfterInsertHooks = append(exampleAfterInsertHooks, exampleHook)
		exampleAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		exampleBeforeUpdateMu.Lock()
		exampleBeforeUpdateHooks = append(exampleBeforeUpdateHooks, exampleHook)
		exampleBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		exampleAfterUpdateMu.Lock()
		exampleAfterUpdateHooks = append(exampleAfterUpdateHooks, exampleHook)
		exampleAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		exampleBeforeDeleteMu.Lock()
		exampleBeforeDeleteHooks = append(exampleBeforeDeleteHooks, exampleHook)
		exampleBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		exampleAfterDeleteMu.Lock()
		exampleAfterDeleteHooks = append(exampleAfterDeleteHooks, exampleHook)
		exampleAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		exampleBeforeUpsertMu.Lock()
		exampleBeforeUpsertHooks = append(exampleBeforeUpsertHooks, exampleHook)
		exampleBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		exampleAfterUpsertMu.Lock()
		exampleAfterUpsertHooks = append(exampleAfterUpsertHooks, exampleHook)
		exampleAfterUpsertMu.Unlock()
	}
}

// One returns a single example record from the query.
func (q exampleQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Example, error) {
	o := &Example{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for example")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Example records from the query.
func (q exampleQuery) All(ctx context.Context, exec boil.ContextExecutor) (ExampleSlice, error) {
	var o []*Example

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Example slice")
	}

	if len(exampleAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Example records in the query.
func (q exampleQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count example rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q exampleQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if example exists")
	}

	return count > 0, nil
}

// Examples retrieves all the records using an executor.
func Examples(mods ...qm.QueryMod) exampleQuery {
	mods = append(mods, qm.From("\"example\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"example\".*"})
	}

	return exampleQuery{q}
}

// FindExample retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindExample(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*Example, error) {
	exampleObj := &Example{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"example\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, exampleObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from example")
	}

	if err = exampleObj.doAfterSelectHooks(ctx, exec); err != nil {
		return exampleObj, err
	}

	return exampleObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Example) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no example provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(exampleColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	exampleInsertCacheMut.RLock()
	cache, cached := exampleInsertCache[key]
	exampleInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			exampleAllColumns,
			exampleColumnsWithDefault,
			exampleColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(exampleType, exampleMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(exampleType, exampleMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"example\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"example\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into example")
	}

	if !cached {
		exampleInsertCacheMut.Lock()
		exampleInsertCache[key] = cache
		exampleInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Example.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Example) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	exampleUpdateCacheMut.RLock()
	cache, cached := exampleUpdateCache[key]
	exampleUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			exampleAllColumns,
			examplePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update example, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"example\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, examplePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(exampleType, exampleMapping, append(wl, examplePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update example row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for example")
	}

	if !cached {
		exampleUpdateCacheMut.Lock()
		exampleUpdateCache[key] = cache
		exampleUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q exampleQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for example")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for example")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ExampleSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), examplePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"example\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, examplePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in example slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all example")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Example) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no example provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(exampleColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	exampleUpsertCacheMut.RLock()
	cache, cached := exampleUpsertCache[key]
	exampleUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			exampleAllColumns,
			exampleColumnsWithDefault,
			exampleColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			exampleAllColumns,
			examplePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert example, could not build update column list")
		}

		ret := strmangle.SetComplement(exampleAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(examplePrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert example, could not build conflict column list")
			}

			conflict = make([]string, len(examplePrimaryKeyColumns))
			copy(conflict, examplePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"example\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(exampleType, exampleMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(exampleType, exampleMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert example")
	}

	if !cached {
		exampleUpsertCacheMut.Lock()
		exampleUpsertCache[key] = cache
		exampleUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Example record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Example) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Example provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), examplePrimaryKeyMapping)
	sql := "DELETE FROM \"example\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from example")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for example")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q exampleQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no exampleQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from example")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for example")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ExampleSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(exampleBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), examplePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"example\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, examplePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from example slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for example")
	}

	if len(exampleAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Example) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindExample(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ExampleSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ExampleSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), examplePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"example\".* FROM \"example\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, examplePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ExampleSlice")
	}

	*o = slice

	return nil
}

// ExampleExists checks if the Example row exists.
func ExampleExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"example\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if example exists")
	}

	return exists, nil
}

// Exists checks if the Example row exists.
func (o *Example) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ExampleExists(ctx, exec, o.ID)
}
